// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC68m_jmWmqh1ZY5NHHPUGvackh2OvOrAs',
    appId: '1:822241813826:web:7704226e4b3c144c0e14db',
    messagingSenderId: '822241813826',
    projectId: 'finio-1b281',
    authDomain: 'finio-1b281.firebaseapp.com',
    storageBucket: 'finio-1b281.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx5QZg4bKCGhRZreM95MPwhtwYsR3WfCU',
    appId: '1:822241813826:android:1240adcaec6714da0e14db',
    messagingSenderId: '822241813826',
    projectId: 'finio-1b281',
    storageBucket: 'finio-1b281.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDij3O1A8fVwHue2Xq93j1AFsgWhFizeVE',
    appId: '1:822241813826:ios:5ca057003671a7d40e14db',
    messagingSenderId: '822241813826',
    projectId: 'finio-1b281',
    storageBucket: 'finio-1b281.firebasestorage.app',
    iosBundleId: 'com.example.mobileAppFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC68m_jmWmqh1ZY5NHHPUGvackh2OvOrAs',
    appId: '1:822241813826:web:926a14f1f267f4b80e14db',
    messagingSenderId: '822241813826',
    projectId: 'finio-1b281',
    authDomain: 'finio-1b281.firebaseapp.com',
    storageBucket: 'finio-1b281.firebasestorage.app',
  );
}
